[default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.15"
ffi = true
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config